xx<-data.frame(stringsAsFactors=FALSE,
   Footywire_name = c("Jake Lever", "Devon Smith", "Jarman Impey",
                      "Hayden Crozier", "Adam Saad", "Jack Watts",
                      "Brendon Ah Chee", "Harley Balic", "Harrison Wigg", "Bryce Gibbs",
                      "Aaron Young", "Logan Austin", "Samuel Murray", "Sam Gibson",
                      "Nathan Wilson", "Matthew Lobbe", "Jake Stringer",
                      "Matthew Kennedy", "Luke Hodge", "Darcy Lang", "Gary Jnr Ablett",
                      "Charlie Cameron", "Lachlan Weller", "Brandon Matera",
                      "Josh Schache"),
        twentyseventeen_club = c("Adelaide", "GWS", "Port Adelaide", "Fremantle",
                      "Gold Coast", "Melbourne", "Port Adelaide", "Fremantle",
                      "Adelaide", "Carlton", "Port Adelaide", "Port Adelaide",
                      "Sydney", "North Melbourne", "GWS", "Port Adelaide",
                      "Western Bulldogs", "GWS", "Hawthorn", "Geelong", "Gold Coast",
                      "Adelaide", "Fremantle", "Gold Coast", "Brisbane"),
        twentyeighteen_club = c("Melbourne", "Essendon", "Hawthorn", "Western Bulldogs",
                      "Essendon", "Port Adelaide", "West Coast", "Melbourne",
                      "Gold Coast", "Adelaide", "Gold Coast", "St Kilda",
                      "Collingwood", "Adelaide", "Fremantle", "Carlton", "Essendon",
                      "Carlton", "Brisbane", "Carlton", "Geelong", "Brisbane",
                      "Gold Coast", "Fremantle", "Western Bulldogs"),
     afltables_id = c("12351", "12029", "12237", "12088", "12330", "11765",
                      "12338", "12512", "yet to debut", "11535", "12068",
                      "12450", "yet to debut", "12093", "12024", "11836", "12167",
                      "12455", "1134", "12286", "1105", "12277", "12385", "11915",
                      "12416")
)
View(xx)
